name: agconnect_applinking_plus
description: AGC App Linking Kit plugin for Flutter.This Kit allows you to create cross-platform links that can work
  as defined regardless of whether your app has been installed by a user.
version: 3.0.1
homepage: https://developer.huawei.com/consumer/en/agconnect/

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.huawei.agc.flutter.applinking
        pluginClass: AppLinkingPlugin
      ios:
        pluginClass: AppLinkingPlugin
